review_version: 3.0
bookname: book
language: ja
booktitle: せつラボ
subtitle: テンプレート
aut: ["aiya000"]
date: 2019-01-14
history: [["XXXX-XX-XX Y"]]
rights: (C) 2019- aiya000 aiya000.develop@gmail.com
debug: null
urnid: urn:uid:http://aiya000.github.io/setulab-template
htmlext: html
stylesheet: ["style.css"]
epubversion: 3
htmlversion: 5
toclevel: 2
secnolevel: 3
toc: true
colophon: true
direction: "ltr"
texstyle: techbooster-doujin
texdocumentclass: ["jsbook", "a5j,twoside,openany,uplatex,9pt"]

epubmaker:
  htmlext: xhtml
  flattoc: true
  flattocindent: true

pdfmaker:
  colophon: true

webmaker:
    stylesheet: ["style.css","style-web.css"]
